### ISSUE TITLE
Glitre price sensor not working anymore

### ISSUE THREAD

**Issue by hansahell** [Danielhiversen/home_assistant_glitre#7]
Error in the logs:
2023-10-05 10:24:42.899 ERROR (MainThread) [custom_components.glitre.data_coordinator] Error fetching Glitre data
Traceback (most recent call last):
File "/config/custom_components/glitre/data_coordinator.py", line 36, in _async_update_data
data["forbruksledd"] = await get_glitre_forbruksledd_data(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/glitre/glitre_api.py", line 25, in get_glitre_forbruksledd_data
grid_tariff = json_resp["gridTariffCollections"][0]["gridTariff"]
~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'gridTariffCollections'
2023-10-05 10:24:42.900 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 233, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 389, in _async_refresh
self.async_update_listeners()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 172, in async_update_listeners
update_callback()
File "/config/custom_components/glitre/sensor.py", line 42, in _handle_coordinator_update
self._attr_native_value = self.coordinator.data["forbruksledd"][
~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'forbruksledd'

**Comment by Danielhiversen** [comment]
The Glite API returns an error. 
I have sent an email to Glitre

**Comment by Danielhiversen** [comment]
I got an answer from Glitre. They say it should be fixed now.
I now get prices, but they are not correct

**Comment by torsteinkern** [comment]
Hello, I just checked the prices and it seems that it is fixed now. Thank!

**Comment by hansahell** [comment]
Yes, seems like they have fixed the problem. The prices are correct now. I contacted Glitre as well but they never got back to me. Closing this ticket.
