### ISSUE TITLE
Errors in the log every night between 00:00 and 01:00

### ISSUE THREAD

**Issue by hansahell** [Danielhiversen/home_assistant_glitre#8]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/glitre/sensor.py:42
integration: Glitre (documentation, issues)
First occurred: 00:00:08 (360 occurrences)
Last logged: 00:59:58

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 258, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 414, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 168, in async_update_listeners
    update_callback()
  File "/config/custom_components/glitre/sensor.py", line 42, in _handle_coordinator_update
    self._attr_native_value = self.coordinator.data["forbruksledd"][
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: datetime.datetime(2024, 4, 23, 22, 0, tzinfo=datetime.timezone.utc)

**Comment by hansahell** [comment]
@Danielhiversen Still a problem and is filling my log file every night. Don't you have this problem?
